### ISSUE TITLE
SRP multiplier is out of bounds

### ISSUE THREAD

**Issue by AuTune** [dhaven/ProtonDriveSync#1]
I keep getting this error every time I try to log in. I am running KeePass 2.5.4 and I have also attached a list of my plugins.
![Screenshot 2023-09-13 123309](https://github.com/dhaven/ProtonDriveSync/assets/122066880/53a28645-37fc-438e-a1d0-aa133fd3628c)

![Screenshot 2023-09-13 123104](https://github.com/dhaven/ProtonDriveSync/assets/122066880/c94e84ca-3428-403f-a8cf-3fc5c0eded89)

**Comment by dhaven** [comment]
Thanks for reporting this issue. I will look into it and get back to you as soon as I find something.

**Comment by AuTune** [comment]
Much appreciated. If you need any additional information about my OS or other information that could help you find the bug I am more than happy to oblige.

**Comment by AuTune** [comment]
Apologies I never saw this, I don't routinely check my Github. Would you still like me to shoot you that email?
