### ISSUE TITLE
Invalid Refresh Token

### ISSUE THREAD

**Issue by aegisofempires** [dhaven/ProtonDriveSync#2]
"Unable to initalize user keys: unable to refresh session: API response contains an error (10013): invalid refresh token.

Plugin no longer working.

**Comment by aegisofempires** [comment]
It now says "A fatal error has occurred!" "SRP multiplier is out of bounds" when I try and log in under a different protonmail account. It only works if I use the previous protonmail account. Please help. I tried reinstalling the plugin to no avail.

**Comment by dhaven** [comment]
Please download latest version of the plugin and let me know if you are still having the issue

=> https://github.com/dhaven/ProtonDriveSync/releases/tag/0.1.3

**Comment by aegisofempires** [comment]
Did not work as it saved as a version that I could not download via app nor web, and a Proton ticket was opened saying the plugin caused an issue with the file. I had to delete and manually upload. I no longer use the plugin for that reason.

**Comment by Micha00000** [comment]
What dhaven, commented on Sep 18, 2023, wrote, works!
