### ISSUE TITLE
Unable to initialize user keys: Value cannot be null.

### ISSUE THREAD

**Issue by ghost** [dhaven/ProtonDriveSync#3]
Hi, so whenever i log in it spits out this error and i cannot open files on drive.
![Screenshot 2023-09-27 070605](https://github.com/dhaven/ProtonDriveSync/assets/64665185/d7234cbf-8ef1-415f-9fd5-cf957e25c611)

Extended error report shows this:

Unable to initialize user keys: Value cannot be null.
Parameter name: source
ProtonDriveSync
   at ProtonDriveSync.StorageProvider.ProtonAPI.<InitUserKeys>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProtonDriveSync.StorageProvider.ProtonDriveStorageProvider.<Init>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProtonDriveSync.ProtonDriveSyncExt.<OnShowSetting>d__8.MoveNext()
Void MoveNext()

Thank you in advance for looking into this.

**Comment by gerald2545** [comment]
Same error here with keepass 2.55 and last version of protondrivesync on Windows 10 pro

**Comment by minogon** [comment]
Same error here with keepass 2.56 and last version 0.1.3 of ProtonDriveSync on Windows 11 pro 23H2

![image](https://github.com/dhaven/ProtonDriveSync/assets/67477340/a10a8906-2539-4283-b9b8-62138fd88fb3)

Unable to initialize user keys: Unable to refresh session: API response contains an error (10013) : Invalid refresh token

**Comment by Cyb3544** [comment]
Same error here with keepass 2.56 and last version 0.1.3 on windows 10 22H2

![image](https://github.com/dhaven/ProtonDriveSync/assets/132453436/3c533120-4a2d-4761-8406-e6575b1a1f7d)

**Comment by retiredBob49** [comment]
Hi Guys,
  I ran into the same problem detailed by grenmel, and found that although proton will allow you to login with just your username, this plugin didn't work until I specified my full email address - username@protonmail.com, not just username. Works fine now.

**Comment by dhaven** [comment]
This has been fixed with release 0.1.4. You can now login with username or email address.
