### ISSUE TITLE
Save to Proton drive fails

### ISSUE THREAD

**Issue by Sharmanh** [dhaven/ProtonDriveSync#8]
I have added the required files to store my DB file on my Proton Drive. I has been working fine for a few weeks. Problem now is: -
1. DB file is opened 100% from Proton Drive.
2. When saving any changes to the DB File - I now get the message
****  Proton drive link to file
****  Failed to save to the specified file!
**** One or more errors occurred
**** The target file might be corrupted. Please try saving again, if that fails, save the database to a different location.

I have tried to rename the file saved on the Proton drive. Saved a new DB file to the Proton Drive. Nothing seems to help. Opens the files with out any problems, but I get the same error every time I try to save the DB.

Keepass 2.56(64Bit)
ProtonDriveSync-0.1.2 - Have downloaded 0.1.3 (Will test shortly)

**Comment by Sharmanh** [comment]
I'm already running ProtonDriveSync-0.1.3

**Comment by dhaven** [comment]
Hi,

I've been working on multiple fixes over the last few months. I hope to ship a new version of the app very soon.

Thanks for your patience!
